### PR TITLE
'accessible' option to improve accessibility of banner.

### PR DESCRIPTION
**Pull request by catatonicprime**
Pretty self-explanatory. Default is to continue to display the banner.

Note: I did not do any version bumping.

### CODE REVIEW

**Comment by lanmaster53** [comment]
I'm not inclined to do this because it seems like an unnecessary change. What's the benefit?

**Comment by catatonicprime** [comment]
literally just making it quieter.

But maybe there are other benefits I have thought much about. Perhaps accessibility? I can't speak on this though, I don't use assistive technologies. But I think I can imagine a screen reader reading:
    _/_/_/    _/_/_/_/    _/_/_/    _/_/_/    _/      _/            _/      _/    _/_/_/

**Comment by lanmaster53** [comment]
So, something I didn't mention before because I wanted to hear your response first was the fact that this is paid ad space. Giving folks that use the software for free the ability to remove the only means of financial support would be unfair to the project and those that are financially supporting the project. In fact, when you look at it that way, it's almost offensive. "Here, give me your software for free and please remove an financial gain from yourself." Not that I think you meant it that way, but it could be seen in that light. If I received donations from the users of Recon-ng rather than relied on support from the ad space, then I would be more than happy to remove myself and any other information from the banner. However, I've received a grand total of one (yes, one) small donation in the 5+ years I've been maintaining this software.

**Comment by catatonicprime** [comment]
It's all good man. Gotta do what's best for you first - I 100% get that.

**Comment by lanmaster53** [comment]
Based on our out-of-band conversation, reopening this to permit modifications towards an accessibility option with simplified ads.

**Comment by catatonicprime** [comment]
Apologies for the long delay - busy busy - you know how it goes.

I'm changing the flag/option name (and the pull request) because the context after our discussion definitely evolved the way I'm thinking about this.

So, I've set a flag all the way up in the framework. This means it should be available to any component (framework included), module, etc. The banner has an alternative, smaller, banner that is read much better. The idea behind this is that some framework components may benefit from alternative outputs in the future too. e.g. Tabled outputs that generate +----+ style outputs. But that can be done at a later time.

Check it out, let me know your thoughts, etc.

**Comment by lanmaster53** [comment]
I may modify further, but am going to merge and test it for now. Please let me know if any of the removed changes had a significant impact on accessibility. Thanks!

**Pull request merged**
