### PR TITLE
Added notes column to ports table.

### PR DESCRIPTION
**Pull request by 0xd0ug**
For your consideration! I edited the code to add a notes column to the ports table, so users can add notes on each port if they want. This will also make it easier to import details like versioning from tools like Nmap. I updated both database creation and migration code and bumped the database to version 9.

### CODE REVIEW

**Comment by lanmaster53** [comment]
Could we be more explicit in what we name the column? Rather than free form data which can lead to inconsistent behavior between modules that may use the columns in different ways, i'd like to see something more explicit like "banner" or something. I want to create an expectation for what goes there. Thoughts?

**Comment by 0xd0ug** [comment]
OK, you got me: I was hoping to put free-form data in there! But failing that, let's use banner. I should explain my motivation--I want to use recon-ng on a test, and I'd like to be able to keep free-form notes about ports so I know which ones I want to come back to. But banner fits -- it's really just more info about the service. Want me to update the code to use "banner" instead?

**Comment by 0xd0ug** [comment]
Closing to resubmit to staging instead of master.

**Comment by 0xd0ug** [comment]
Reopened because I realized you're working in staging -- let me know if you want me to move this to staging after you're done with the API and I will.

**Comment by lanmaster53** [comment]
Yes, please resubmit to staging. I'll merge there and add the other stuff we talked about before merging it all to master. Thanks!

**Comment by 0xd0ug** [comment]
Will do, closing this and recreating under staging.

**Pull request closed without merging**
