### PR TITLE
Specify jsonschema version 2.6.0 in REQUIREMENTS. Addresses issue #61

### PR DESCRIPTION
**Pull request by jabberwock**
While executing `pip install -r REQUIREMENTS` I received an error about flasgger requirement jasonschema < 3.0.0. However, python 3.6+ will install a newer version. This explicitly sets the version number to address this issue.

### CODE REVIEW

**Comment by jabberwock** [comment]
Created PR https://github.com/lanmaster53/recon-ng/pull/62

**Comment by lanmaster53** [comment]
Ok, so I don't want to specify the dependencies of dependencies in the requirements file. Just the top level dependencies should be specified, then the lower level dependencies should resolve properly based on the top level version. If not, then we can specify onesies and twosies as needed.

**Comment by lanmaster53** [comment]
Thinking a bit more, I believe we could just add `jsonschema==2.6.0` to the end of the file and that would resolve the issue as well. Or, I could just officially say that 3.8 isn't supported yet. Which I am inclined to do until 3.8 becomes mainstream. I find it odd that an older version of the library works with the new version of Python and not the other way around.

**Comment by jabberwock** [comment]
I received the same behavior in several 3.6.0 and up versions. And I agree - it is strange.

**Comment by lanmaster53** [comment]
Check the related issue. Let's continue the dialogue there. I'm going to close this PR for now and will manually update the framework when we come to a logical conclusion. Thanks!

**Pull request closed without merging**
